# Configurações do repositório GitHub
# Este arquivo configura o repositório automaticamente quando pushado para a branch main

repository:
  name: docker-php-dev
  description: Ambiente de desenvolvimento Docker com PHP 8.3, MySQL 8.0, Nginx e phpMyAdmin
  homepage: https://github.com/seu-usuario/docker-php-dev
  topics: docker, php, mysql, nginx, phpmyadmin, development, environment, docker-compose
  
  # Configurações do repositório
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  
  # Configurações padrão
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  
  # Deletar branch após merge
  delete_branch_on_merge: true
  
  # Configurações de segurança
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Configurações de branches
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts:
          - "Test Docker PHP Environment"
      enforce_admins: false
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false

# Configurações de labels
labels:
  - name: bug
    color: d73a4a
    description: Algo não está funcionando
  - name: documentation
    color: 0075ca
    description: Melhorias ou adições à documentação
  - name: duplicate
    color: cfd3d7
    description: Esta issue ou pull request já existe
  - name: enhancement
    color: a2eeef
    description: Novo recurso ou solicitação de melhoria
  - name: good first issue
    color: 7057ff
    description: Bom para iniciantes
  - name: help wanted
    color: 008672
    description: Contribuições extras são bem-vindas
  - name: invalid
    color: e4e669
    description: Isso não parece certo
  - name: question
    color: d876e3
    description: Mais informações são necessárias
  - name: wontfix
    color: ffffff
    description: Isso não será trabalhado

# Configurações de colaboradores
collaborators:
  - username: seu-usuario
    permission: admin

# Configurações de times
teams:
  - name: developers
    permission: push
  - name: maintainers
    permission: admin